version: '3.7'

services:
  mysql:
    image: parcial_2_bd
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
        - mynetwork
    deploy:
      replicas: 1 

  service-nodejs:
    image: restparcial_2_rest
    ports:
      - "5050:3000"
    networks:
      - mynetwork
    deploy:
      replicas: 1 

  service-soap:
    image: parcial_2_soap
    ports:
      - "4000:4000"
    networks:
      - mynetwork
    deploy:
      replicas: 1

  service-cliente   :
    image: parcial_2_front
    ports:
      - "8080:80"
    networks:
      - mynetwork
    deploy:
      replicas: 4 
  
  

networks:
  mynetwork:
